#!/usr/bin/python

import os
import re
import subprocess
import sys
import urllib2
import rsvprobe
import re
import ConfigParser
import socket

sys.path.insert(0, '.')


class DummyVanillaProbe(rsvprobe.RSVProbe):
    """
    This probes just tests it can run. Usefull for debuggin any site including non OSG sites
    """

    def __init__(self):
        rsvprobe.RSVProbe.__init__(self)
        self.metric = ""
        self.short_metric = ""
        metric = rsvprobe.RSVMetric("Dummy-Vanilla-Probe",
                 "org.osg.general.dummy-vanilla-probe", rsvprobe.RSVMetric.STATUS)
        self.supported_metrics = [metric]
        self.details = "---\n"

    def parseopt(self):
        """parse options specific to the gfactory probe
        """
        options, optlist, remainder = rsvprobe.RSVProbe.parseopt(self)
        for opt, arg in options:
            if self.host == self.localhost:
                self.is_local = True
            else:
                self.is_local = False
        return options, optlist, remainder

    def run(self):
        """Main routine for the probe"""
        self.parseopt()
        hostname = socket.gethostname()
        self.add_message("Host: %s" % hostname)
        self.return_ok("Everything OK")

def main():
    probe = DummyVanillaProbe()
    return probe.run()

if __name__ == '__main__':
    sys.exit(main())
